// <auto-generated />
using System;
using App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206231220_seed_data")]
    partial class seed_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.DeckWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlashcardCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardCategoryId");

                    b.ToTable("DeckWords");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PracticeId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.FlashcardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.ToTable("FlashcardCategories");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.FlashcardOldSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("FlashcardCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardCategoryId");

                    b.HasIndex("FlashcardId");

                    b.ToTable("FlashcardOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.FlashcardSessionRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlashcardOldSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardOldSessionId");

                    b.ToTable("FlashcardSessionRows");
                });

            modelBuilder.Entity("App.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.DeckVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListeningCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningCategoryId");

                    b.ToTable("DeckVideos");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.Listening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PracticeId");

                    b.ToTable("Listenings");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.ListeningCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ListeningId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningId");

                    b.ToTable("ListeningCategories");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.ListeningOldSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ListeningCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ListeningId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningCategoryId");

                    b.HasIndex("ListeningId");

                    b.ToTable("ListeningOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.ListeningSessionRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListenedSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListeningOldSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Similarity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningOldSessionId");

                    b.ToTable("ListeningSessionRows");
                });

            modelBuilder.Entity("App.Domain.Entities.Practice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Practices");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PracticeId");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.ReadingBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeftColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReadingId")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId");

                    b.ToTable("ReadingBooks");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.ReadingOldSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReadingBookId")
                        .HasColumnType("int");

                    b.Property<int>("ReadingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReadingBookId");

                    b.HasIndex("ReadingId");

                    b.ToTable("ReadingOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.ReadingSessionRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerTranslate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadingOldSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SelectedSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Similarity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReadingOldSessionId");

                    b.ToTable("ReadingSessionRows");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.Writing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PracticeId");

                    b.ToTable("Writings");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.WritingBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeftColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WritingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WritingId");

                    b.ToTable("WritingBooks");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.WritingOldSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WritingBookId")
                        .HasColumnType("int");

                    b.Property<int>("WritingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WritingBookId");

                    b.HasIndex("WritingId");

                    b.ToTable("WritingOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.WritingSessionRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerTranslate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Similarity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WritingOldSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WritingOldSessionId");

                    b.ToTable("WritingSessionRows");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.DeckWord", b =>
                {
                    b.HasOne("App.Domain.Entities.FlashcardEntities.FlashcardCategory", "FlashcardCategory")
                        .WithMany("DeckWords")
                        .HasForeignKey("FlashcardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardCategory");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.Flashcard", b =>
                {
                    b.HasOne("App.Domain.Entities.Language", "Language")
                        .WithMany("Flashcards")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.Practice", "Practice")
                        .WithMany("Flashcards")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.FlashcardCategory", b =>
                {
                    b.HasOne("App.Domain.Entities.FlashcardEntities.Flashcard", "Flashcard")
                        .WithMany("FlashcardCategories")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.FlashcardOldSession", b =>
                {
                    b.HasOne("App.Domain.Entities.FlashcardEntities.FlashcardCategory", "FlashcardCategory")
                        .WithMany("FlashcardOldSessions")
                        .HasForeignKey("FlashcardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.FlashcardEntities.Flashcard", "Flashcard")
                        .WithMany("FlashcardOldSessions")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("FlashcardCategory");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.FlashcardSessionRow", b =>
                {
                    b.HasOne("App.Domain.Entities.FlashcardEntities.FlashcardOldSession", "FlashcardOldSession")
                        .WithMany("FlashcardSessionRows")
                        .HasForeignKey("FlashcardOldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardOldSession");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.DeckVideo", b =>
                {
                    b.HasOne("App.Domain.Entities.ListeningEntities.ListeningCategory", "ListeningCategory")
                        .WithMany("DeckVideos")
                        .HasForeignKey("ListeningCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeningCategory");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.Listening", b =>
                {
                    b.HasOne("App.Domain.Entities.Language", "Language")
                        .WithMany("Listenings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.Practice", "Practice")
                        .WithMany("Listenings")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.ListeningCategory", b =>
                {
                    b.HasOne("App.Domain.Entities.ListeningEntities.Listening", "Listening")
                        .WithMany("ListeningCategories")
                        .HasForeignKey("ListeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listening");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.ListeningOldSession", b =>
                {
                    b.HasOne("App.Domain.Entities.ListeningEntities.ListeningCategory", "ListeningCategory")
                        .WithMany("ListeningOldSessions")
                        .HasForeignKey("ListeningCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.ListeningEntities.Listening", "Listening")
                        .WithMany("ListeningOldSessions")
                        .HasForeignKey("ListeningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Listening");

                    b.Navigation("ListeningCategory");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.ListeningSessionRow", b =>
                {
                    b.HasOne("App.Domain.Entities.ListeningEntities.ListeningOldSession", "ListeningOldSession")
                        .WithMany("ListeningSessionRows")
                        .HasForeignKey("ListeningOldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeningOldSession");
                });

            modelBuilder.Entity("App.Domain.Entities.Practice", b =>
                {
                    b.HasOne("App.Domain.Entities.Language", "Language")
                        .WithMany("Practices")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.Reading", b =>
                {
                    b.HasOne("App.Domain.Entities.Language", "Language")
                        .WithMany("Readings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.Practice", "Practice")
                        .WithMany("Readings")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.ReadingBook", b =>
                {
                    b.HasOne("App.Domain.Entities.ReadingEntities.Reading", "Reading")
                        .WithMany("ReadingBooks")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.ReadingOldSession", b =>
                {
                    b.HasOne("App.Domain.Entities.ReadingEntities.ReadingBook", "ReadingBook")
                        .WithMany("ReadingOldSessions")
                        .HasForeignKey("ReadingBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.ReadingEntities.Reading", "Reading")
                        .WithMany("ReadingOldSessions")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reading");

                    b.Navigation("ReadingBook");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.ReadingSessionRow", b =>
                {
                    b.HasOne("App.Domain.Entities.ReadingEntities.ReadingOldSession", "ReadingOldSession")
                        .WithMany("ReadingSessionRows")
                        .HasForeignKey("ReadingOldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingOldSession");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.Writing", b =>
                {
                    b.HasOne("App.Domain.Entities.Language", "Language")
                        .WithMany("Writings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.Practice", "Practice")
                        .WithMany("Writings")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.WritingBook", b =>
                {
                    b.HasOne("App.Domain.Entities.WritingEntities.Writing", "Writing")
                        .WithMany("WritingBooks")
                        .HasForeignKey("WritingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Writing");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.WritingOldSession", b =>
                {
                    b.HasOne("App.Domain.Entities.WritingEntities.WritingBook", "WritingBook")
                        .WithMany("WritingOldSessions")
                        .HasForeignKey("WritingBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.WritingEntities.Writing", "Writing")
                        .WithMany("WritingOldSessions")
                        .HasForeignKey("WritingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Writing");

                    b.Navigation("WritingBook");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.WritingSessionRow", b =>
                {
                    b.HasOne("App.Domain.Entities.WritingEntities.WritingOldSession", "WritingOldSession")
                        .WithMany("WritingSessionRows")
                        .HasForeignKey("WritingOldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WritingOldSession");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.Flashcard", b =>
                {
                    b.Navigation("FlashcardCategories");

                    b.Navigation("FlashcardOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.FlashcardCategory", b =>
                {
                    b.Navigation("DeckWords");

                    b.Navigation("FlashcardOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.FlashcardEntities.FlashcardOldSession", b =>
                {
                    b.Navigation("FlashcardSessionRows");
                });

            modelBuilder.Entity("App.Domain.Entities.Language", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("Listenings");

                    b.Navigation("Practices");

                    b.Navigation("Readings");

                    b.Navigation("Writings");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.Listening", b =>
                {
                    b.Navigation("ListeningCategories");

                    b.Navigation("ListeningOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.ListeningCategory", b =>
                {
                    b.Navigation("DeckVideos");

                    b.Navigation("ListeningOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.ListeningEntities.ListeningOldSession", b =>
                {
                    b.Navigation("ListeningSessionRows");
                });

            modelBuilder.Entity("App.Domain.Entities.Practice", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("Listenings");

                    b.Navigation("Readings");

                    b.Navigation("Writings");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.Reading", b =>
                {
                    b.Navigation("ReadingBooks");

                    b.Navigation("ReadingOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.ReadingBook", b =>
                {
                    b.Navigation("ReadingOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.ReadingEntities.ReadingOldSession", b =>
                {
                    b.Navigation("ReadingSessionRows");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.Writing", b =>
                {
                    b.Navigation("WritingBooks");

                    b.Navigation("WritingOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.WritingBook", b =>
                {
                    b.Navigation("WritingOldSessions");
                });

            modelBuilder.Entity("App.Domain.Entities.WritingEntities.WritingOldSession", b =>
                {
                    b.Navigation("WritingSessionRows");
                });
#pragma warning restore 612, 618
        }
    }
}
