# CLIENT - OTEL COLLECTOR - BACKEND
  # RECEIVERS VE EXPORTERS "CLIENT VE OTEL COLLECTOR" ARASINDA VEYA "OTEL COLLECTOR VE BACKEND" ARASINDA VARDIR.
  # BUNLAR BİRBİRLERİYLE KARIŞTIRILMAMALIDIR.

  # RECEIVERS KISMINDA BELİRTİLENLER CLIENT İLE OTEL COLLECTOR ARASINDAKİ KONFİGÜRASYONU BELİRTİR.
    # PUSH BASED RECEIVERS VEYAHUT PULL BASED RECEIVERS OLABİLİR.
      # PUSH BASED RECEIVERS --> CLIENT VERİYİ OTEL COLLECTOR'A PUSH EDER. BURADA EXPORTER İSE CLIENT TARAFINDA BELİRTİLİR.
        # BURADA EXPORTER CLIENT TARAFIDIR ÖRNEĞİN "import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-grpc'"
      # PULL BASED RECEIVERS --> OTEL COLLECTOR VERİYİ CLIENT'DAN PULL EDER.
        # BURADA EXPORTER KAVRAMI YOKTUR.

  # EXPORTERS KISMINDA BELİRTİLENLER OTEL COLLECTOR İLE BACKEND ARASINDAKİ KONFİGÜRASYONU BELİRTİR.
    # PUSH BASED EXPORTERS VEYAHUT PULL BASED EXPORTERS OLABİLİR.
      # PUSH BASED EXPORTERS --> OTEL COLLECTOR VERİYİ BACKEND'E PUSH EDER.
        # BURADA RECEIVER BACKEND TARAFIDIR ÖRNEĞİN JAEGER İÇİN "jaeger-all-in-one" CONTAINER'I.
      # PULL BASED EXPORTERS --> BACKEND VERİYİ OTEL COLLECTOR'DAN PULL EDER.İ
        # BURADA RECEIVER KAVRAMI YOKTUR.

receivers:
  otlp: # --> PUSH BASED RECEIVER
    protocols:
      grpc: # DEFAULT --> 4317
        endpoint: ${RECEIVER_OTLP_GRPC_ENDPOINT} # "ANLAMI --> COLLECTOR 4317 PORTUNU AÇ VE BURADA VERİ BEKLE. VERİ BEKLEYECEĞİN ADRESLER ŞUAN İÇİN TÜM IP ADRESLERİ."
      http: # DEFAULT --> 4318
        endpoint: ${RECEIVER_OTLP_HTTP_ENDPOINT} # "ANLAMI --> COLLECTOR 4318 PORTUNU AÇ VE BURADA VERİ BEKLE. VERİ BEKLEYECEĞİN ADRESLER ŞUAN İÇİN TÜM IP ADRESLERİ."

# PUSH BASED BACKENDS --> VERİLER COLLECTOR'DAN BACKEND'E PUSH EDİLİR. YANİ COLLECTOR BELİRTİLEN ENDPONIT'E (HEDEF BACKEND) VERİYİ PUSH EDER.
# PULL BASED BACKENDS --> BACKEND VERİLERİ COLLECTOR'DAN PULL EDER. YANİ COLLECTOR'UN KENDİ AÇTIĞI ADRESTİR. HEDEF BACKEND BU ENDPOINT'I SCRAPE EDER. PULL BASED EXPORTER'LAR COLLECTOR İÇİNDE ÇALIŞIRLAR.
# BU YÜZDEN OTLE-COLLECTOR'U SCRAPE EDERLER.
exporters:
  otlp:
    endpoint: ${EXPORTER_OTLP_ENDPOINT}
    tls:
      insecure: true

  # DATA SOURCES: TRACES
  otlp_grpc/jaeger:
    endpoint: ${EXPORTER_OTLP_JAEGER_ENDPOINT}
    tls:
      insecure: true

  # DATA SOURCES: METRICS
  prometheus:
    endpoint: ${EXPORTER_PROMETHEUS_ENDPOINT}
    namespace: default

  # DATA SOURCES: LOGS
  elasticsearch:
    endpoints: ["${ELASTIC_URL}"]
    logs_index: ${ELASTIC_INDEX}
    mapping:
      mode: ecs

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp_grpc/jaeger]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [elasticsearch]
