namespace App.Application.Contracts.Persistence;

// OUR PURPOSE IS TO PERFORM DATABASE OPERATIONS THROUGH A SINGLE TRANSACTION.
// IN ASYNCHRONOUS OPERATIONS, TASK CORRESPONDS TO VOID.
public interface IUnitOfWork
{
    /// <summary>
    /// ASYNCHRONOUSLY SAVES ALL CHANGES MADE IN THIS CONTEXT TO THE UNDERLYING DATABASE.
    /// </summary>
    Task<int> CommitAsync();
}